-- MySQL Script generated by MySQL Workbench
-- Wed Feb 28 15:02:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tapro_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tapro_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tapro_db` DEFAULT CHARACTER SET utf8 ;
USE `tapro_db` ;

-- -----------------------------------------------------
-- Table `tapro_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`user` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NULL,
  `user_full_name` VARCHAR(45) NULL,
  `hashed_password` VARCHAR(60) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `hashed_password_UNIQUE` (`hashed_password` ASC) VISIBLE,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `created_by_user_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`functions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`functions` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`functions` (
  `function_id` INT NOT NULL,
  `function_name` INT NULL,
  PRIMARY KEY (`function_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`users_function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`users_function` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`users_function` (
  `user_id` INT NOT NULL,
  `function_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `function_id`),
  INDEX `function_id_functions_user_idx` (`function_id` ASC) VISIBLE,
  CONSTRAINT `user_id_functions_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `function_id_functions_user`
    FOREIGN KEY (`function_id`)
    REFERENCES `tapro_db`.`functions` (`function_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`job_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`job_role` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`job_role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`team` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`team` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NOT NULL,
  `team_description` VARCHAR(150) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `created_by_team_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`org_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`org_unit` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`org_unit` (
  `org_unit_id` INT NOT NULL,
  `unit_name` VARCHAR(45) NULL,
  `description` VARCHAR(150) NULL,
  `parent_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`org_unit_id`),
  INDEX `parent_id_org_unit_idx` (`parent_id` ASC) VISIBLE,
  UNIQUE INDEX `parent_id_UNIQUE` (`parent_id` ASC) VISIBLE,
  UNIQUE INDEX `org_unit_id_UNIQUE` (`org_unit_id` ASC) VISIBLE,
  INDEX `created_by_orgunit_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `parent_id_org_unit`
    FOREIGN KEY (`parent_id`)
    REFERENCES `tapro_db`.`org_unit` (`org_unit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_orgunit_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`resource` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`resource` (
  `resource_id` VARCHAR(10) NOT NULL,
  `resource_name` VARCHAR(45) NULL,
  `role_id` INT NULL,
  `org_unit_id` INT NULL,
  `team_id` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `role_id_resources_idx` (`role_id` ASC) VISIBLE,
  INDEX `team_id_resources_idx` (`team_id` ASC) VISIBLE,
  INDEX `org_unit_id_resources_idx` (`org_unit_id` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `role_id_resources`
    FOREIGN KEY (`role_id`)
    REFERENCES `tapro_db`.`job_role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `team_id_resources`
    FOREIGN KEY (`team_id`)
    REFERENCES `tapro_db`.`team` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `org_unit_id_resources`
    FOREIGN KEY (`org_unit_id`)
    REFERENCES `tapro_db`.`org_unit` (`org_unit_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_resource_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`criticality_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`criticality_type` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`criticality_type` (
  `criticality_id` INT NOT NULL,
  `description` VARCHAR(150) NULL,
  `type` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`criticality_id`),
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `created_by_crittype_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`project` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL,
  `pro_start_date` DATE NULL,
  `pro_end_date` DATE NULL,
  `criticality_id` INT NULL,
  `project_manager` VARCHAR(10) NULL,
  `dilevery_manager` VARCHAR(10) NULL,
  `description` VARCHAR(150) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `criticality_id_criticality_type_idx` (`criticality_id` ASC) VISIBLE,
  INDEX `project_manager_delivery_manager_user_idx` (`project_manager` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  INDEX `delivery_manager_user_idx` (`dilevery_manager` ASC) VISIBLE,
  CONSTRAINT `criticality_id_criticality_type`
    FOREIGN KEY (`criticality_id`)
    REFERENCES `tapro_db`.`criticality_type` (`criticality_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `project_manager_user`
    FOREIGN KEY (`project_manager`)
    REFERENCES `tapro_db`.`resource` (`resource_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_project_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `delivery_manager_user`
    FOREIGN KEY (`dilevery_manager`)
    REFERENCES `tapro_db`.`resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`task` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NULL,
  `ex_start_date` DATE NULL,
  `ex_end_date` DATE NULL,
  `description` VARCHAR(150) NULL,
  `project_id` INT NULL,
  `task_allocation_percentage` INT NULL,
  `task_progress_percentage` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `project_id_project_idx` (`project_id` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `project_id_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `tapro_db`.`project` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_task_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`holiday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`holiday` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`holiday` (
  `holy_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `holy_type` TINYINT NULL,
  PRIMARY KEY (`holy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`resource_leaves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`resource_leaves` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`resource_leaves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resource_id` VARCHAR(45) NULL,
  `holy_id` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `resource_id_resources_idx` (`resource_id` ASC) VISIBLE,
  INDEX `holy_id_holiday_idx` (`holy_id` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `resource_id_resources`
    FOREIGN KEY (`resource_id`)
    REFERENCES `tapro_db`.`resource` (`resource_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `holy_id_holiday`
    FOREIGN KEY (`holy_id`)
    REFERENCES `tapro_db`.`holiday` (`holy_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_leaves_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`sprint` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`sprint` (
  `sprint_id` INT NOT NULL AUTO_INCREMENT,
  `sprint_name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`sprint_id`),
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `created_by_sprint_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tapro_db`.`resource_allocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tapro_db`.`resource_allocation` ;

CREATE TABLE IF NOT EXISTS `tapro_db`.`resource_allocation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sprint_id` INT NOT NULL,
  `resource_id` VARCHAR(45) NOT NULL,
  `task_id` INT NULL,
  `percentage` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `sprint_id_sprint_idx` (`sprint_id` ASC) VISIBLE,
  INDEX `resource_id_resource_idx` (`resource_id` ASC) VISIBLE,
  INDEX `task_id_tasks_idx` (`task_id` ASC) VISIBLE,
  INDEX `created_by_fk_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `sprint_id_sprint`
    FOREIGN KEY (`sprint_id`)
    REFERENCES `tapro_db`.`sprint` (`sprint_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resource_id_resource`
    FOREIGN KEY (`resource_id`)
    REFERENCES `tapro_db`.`resource` (`resource_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_id_tasks`
    FOREIGN KEY (`task_id`)
    REFERENCES `tapro_db`.`task` (`task_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `created_by_res_alloc_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `tapro_db`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
